### ISSUE TITLE
Once VSP token transferred to multisig in Avalanche pool, propose transaction to multisig for rewards refill

### ISSUE THREAD

**Issue by patidarmanoj10** [vesperfi/vesper-pool-ops#107]
WETH: 2000
DAI: 4000
USDC: 4000
WBTC: 2000
Avax: 30000

**Comment by virendrapatidar** [comment]
@patidarmanoj10 - Want to double confirm rewards for Avax is 30000 and not 3000 ?

**Comment by virendrapatidar** [comment]
Proposed 3 txns

```
Nonce 18, 19 and 20
vaWETH : nonce 18
vaAVAX : nonce 19 and
vaDAI, vaUSDC and vaWBTC : nonce 20

```
Details [here](https://gnosis-safe.io/app/avax:0x98ca142b7a7856375d665B58A64FB6D29b49eF1f/transactions/queue)
