### ISSUE TITLE
Update weight of Avalanche strategies.

### ISSUE THREAD

**Issue by patidarmanoj10** [vesperfi/vesper-pool-ops#110]
Update weight based on spot APY on external protocol.

AVAX: 
Benqi: 97%

WBTC:
TradeJoe: 97%

WETH:
TradeJoeLeverage: 97%

DAI:
Benqi : 97%

USDC:
TradeJoeLeverage: 97%

**Comment by virendrapatidar** [comment]
Weight update done except for weth pool
[PR](https://github.com/vesperfi/vesper-pool-ops/pull/111/files) 9 lines changed
[18 txn submitted](https://snowtrace.io/address/0x76d266DFD3754f090488ae12F6Bd115cD7E77eBD) - one each for weight update and rebalance.
