### ISSUE TITLE
Updated weight of Avalanche strategies

### ISSUE THREAD

**Issue by rokso** [vesperfi/vesper-pool-ops#112]
As per request from @zhhuffman update weight as follows

AVAX
- TraderJoe - 0%
- BenqiLeverage - 97%

WETH
- Aave - 0%
- TraderJoeLeverage - 97%

**Comment by virendrapatidar** [comment]
As requested, weight was updated for 4 strategies (reduce for 2 and increase for 2).

4 updateDebtRatio and 4 rebalance is done.
Details [here](https://snowtrace.io/address/0x76d266DFD3754f090488ae12F6Bd115cD7E77eBD)
