### ISSUE TITLE
Update weight of Avalanche WBTC strategy

### ISSUE THREAD

**Issue by rokso** [vesperfi/vesper-pool-ops#114]
> Once BenqiLeverage new version is deployed, update weight as below.

WBTC:
- TraderJoeStrategy: 0%
- BenqiLeverage: 97%

**Comment by virendrapatidar** [comment]
Benqi leverage Strategy is [deployed](https://github.com/bloqpriv/vesper-pools-v3/issues/1224#issuecomment-1108922807). Will open PR once multisig are signed.
Multisig Nonce 33 : updateFeeCollector
Multisig Nonce 34 : migrateStrategy
