### ISSUE TITLE
Update weight of Avalanche USDC strategies

### ISSUE THREAD

**Issue by rokso** [vesperfi/vesper-pool-ops#118]
vaUSDC Pool
- Benqi: 0%
- Alpha Homora: 97%

**Comment by virendrapatidar** [comment]
@rokso 

Updated weight directly in poolAccountant contract for now.
https://snowtrace.io/address/0x76d266DFD3754f090488ae12F6Bd115cD7E77eBD

Since, we are making pool name change, I will generate avalanche.csv again with correct value and raise PR once all updates are done.

**Comment by rokso** [comment]
@virendrapatidar more updates

WBTC Pool:
- BenqiLeverage down to  50%
- Curve: 25%
- Alpha Homora: 23%

**Comment by virendrapatidar** [comment]
WBTC weight update done as mentioned above.
Details here : https://snowtrace.io/address/0x76d266DFD3754f090488ae12F6Bd115cD7E77eBD

**Comment by rokso** [comment]
@virendrapatidar Another update
vaUSDC
- Benqi leverage 50%
- Alpha down to 47%

**Comment by virendrapatidar** [comment]
vaUSDC weight updated as well.
