### ISSUE TITLE
vaWBTC.e: Move all weight from Benqi leverage to TradeJoe deposit strategy

### ISSUE THREAD

**Issue by patidarmanoj10** [vesperfi/vesper-pool-ops#120]
At the moment of creating this GH issue, TraderJoeCompoundStrategyAvalancheWBTC yielding 1.6% which is higher than leverage in Benqi

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @zhhuffman 
Let me know whenever you want to update this weight.
