### ISSUE TITLE
Updated weight for WBTC.e on Avalanche

### ISSUE THREAD

**Issue by rokso** [vesperfi/vesper-pool-ops#121]
WBTC.e:
- Benqi: 0%
- AlphaLend: 0%
- Curve: 97%

**Comment by virendrapatidar** [comment]
Curve rebalance is failing and @rokso  is checking it.
We set Benqi to 1% as of now as with 0% rebalance was failing for Benqi as well.

**Comment by rokso** [comment]
We have found some issue in Curve strategy and all fund will be withdrawn from Curve. @green-jeff

**Comment by patidarmanoj10** [comment]
@green-jeff traderjoe has 1.3% apy.  Curve has some issue.  should we set all weight to tradejoe?

**Comment by green-jeff** [comment]
@rokso @patidarmanoj10 BenQi leverage strategy is good again, let's close out for now. Looks like they had intermittence in rewards.

Gross APY on BenQi Leverage (60% LTV) is now 5.68% gross APR

BenQi Leverage: 97% weight

**Comment by patidarmanoj10** [comment]
Not sure why APY suddenly dropped. Lets remove from benqi levergae again and set this weight to tradejoe

**Comment by patidarmanoj10** [comment]
wbtc.e : 47% homora, 50% traderjoe

**Comment by virendrapatidar** [comment]
Updated ->> wbtc.e : 47% homora, 50% traderjoe
