### ISSUE TITLE
Update vaUSDC Weight on Mainnet

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#123]
Weight
* Convex4pool: 95%

**Comment by green-jeff** [comment]
Bump @virendrapatidar @patidarmanoj10

**Comment by green-jeff** [comment]
Pinging here @virendrapatidar @patidarmanoj10

**Comment by virendrapatidar** [comment]
@green-jeff updated weight to 95% and rebalanced.
