### ISSUE TITLE
Deploy IronBank Strategy for vaETH

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#125]
Deploy the following strategy to vaETH:

1. Deposit ETH
2. Borrow DAI at 60% LTV
3. Deposit DAI to vaDAI

60% LTV is 70% of the maximum 85% LTV supported on IronBank for ETH collateral.

**Comment by virendrapatidar** [comment]
@green-jeff 
IronBank Borrow DAI is deployed for vaETH. Need weight details. It should be >23% to be able to work with vaETH pool due to fund locked in Rari#8

**Comment by green-jeff** [comment]
Looking to deploy here, pulling some TVL from Maker. Better APY and more effective collateralization healthy for vaDAI pool too

**Comment by patidarmanoj10** [comment]
@green-jeff We dont want to enable IronBank also. correct?  can I close this item?

**Comment by green-jeff** [comment]
correct
