### ISSUE TITLE
Deploy Aave Borrow Strategy for vaETH on mainnet (FEI)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#128]
Deploy Deposit Borrow Vesper XY Strategy for vaETH as follows:
1. Deposit ETH to Aave
2. Borrow FEI at 55% LTV
3. Deposit to vaFEI

55% LTV on ETH is roughly 70% of the maximum LTV (82.5%) supported by Aave for ETH collateral.

**Comment by virendrapatidar** [comment]
@green-jeff - 
This is deployed now. Please suggest weight for it. I will gradually increment the weight and test it on mainnet.

**Comment by virendrapatidar** [comment]
It has 1% weight for now but For vaETH, new XY strategy must allocate weight > 23% and the same amount of weight we need to reduce for the existing maker strategy to make it work. vaETH has some fund locked due to Rari#8
