### ISSUE TITLE
Deploy Aave Borrow Strategy for vaETH on mainnet (FRAX)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#129]
Deploy Deposit Borrow Vesper XY Strategy for vaETH as follows:
1. Deposit ETH to Aave
2. Borrow FRAX at 55% LTV
3. Deposit to vaFRAX

55% LTV on ETH is roughly 70% of the maximum LTV (82.5%) supported by Aave for ETH collateral.

**Comment by virendrapatidar** [comment]
@green-jeff  - This has lower priority for now. 
Let me know when we need to deploy it.
