### ISSUE TITLE
Deploy Aave Borrow strategy for vaWBTC (FRAX) on mainnet

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#131]
Deploy Deposit Borrow Vesper XY Strategy for vaWBTC as follows:
1. Deposit WBTC to Aave
2. Borrow FRAX at 50% LTV
3. Deposit to vaFRAX

50% LTV on WBTC is roughly 70% of the maximum LTV (70%) supported by Aave for WBTC collateral.

**Comment by virendrapatidar** [comment]
@green-jeff - This has lower priority for now.
Let me know when we need to deploy it.
