### ISSUE TITLE
Avalanche wBTC.e weight rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#133]
Reweight WBTC.e pool as follows:

* Banker Joe: 50%
* BenQi Leverage: 20%
* Alpha Homora: 28%

Alpha Homora market is very small. Pulling some of our position out will increase APY naturally.

BenQi Leverage APY has been very good, but moves quickly. Don't want to put pool into negative APY earnings.

Current gross APY: 1.58%

Projected gross APY: 2.12% (excludes Alpha Homora APY increase)

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 

Trader Joe: 50% - Was already set.
BenQi Leverage: 20% - Updated
Alpha Homora: 28% - Updated
