### ISSUE TITLE
Avalanche USDC.n weight rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#134]
Update weight as follows:

* Alpha Homora: 27%
* BenQi Leverage: 70%

Use 70% LTV for BenQi (maximum supported LTV is 80%)

Very good APY on BenQi lev. Leave some TVL on avalanche as it will naturally increase APY

Current gross APY: 2.15%

Projected gross APY: 7.75%

**Comment by virendrapatidar** [comment]
@green-jeff 

Updated as mentioned.
Alpha Homora: 27%
BenQi Leverage: 70%
