### ISSUE TITLE
AVAX pool weight rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#135]
Update AVAX pool strategy weights as follows:

* Alpha Homora: 70%
* Trader Joe Leverage (65% LTV): 27%

Maximum LTV on AVAX on Trader Joe is 75%

Small market on Trader Joe. Move limited funds to ensure it doesn't unbalance and produce negative APY

Current gross APY: 4.03%
Projected gross APY: 5.21%

**Comment by virendrapatidar** [comment]
@green-jeff cc @patidarmanoj10 

Alpha Homora: 70% set to 70%
Trader Joe Leverage is being used for the first time. I will do gradual weight in a few hours with multiple rebalances. Starting first rebalance with 1% weight.

**Comment by virendrapatidar** [comment]
Updated weight for Trader Joe Leverage to 3% and rebalanced.

**Comment by virendrapatidar** [comment]
Updated weight for Trader Joe Leverage to 10% and rebalanced.

**Comment by virendrapatidar** [comment]
Updated weight for Trader Joe Leverage to 27% and rebalanced.
