### ISSUE TITLE
Avalanche DAI.e pool weight rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#136]
Update DAI weight as follows:
* BenQi Leverage (75% LTV): 97%

Maximum LTV supported is 82.5% on DAI.

Very strong leverage APY on BenQi. Should take advantage.

Current gross APY: 3.05%
Projected gross APY: 12.96%

**Comment by virendrapatidar** [comment]
@green-jeff 

As mentioned, Updated weight for BenQi Leverage to 97%
