### ISSUE TITLE
Weight Update for vaWBTC (mainnet) - New Deposit-Borrow Strategies

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#138]
Looking to take advantage of WBTC Deposit-Borrow opportunities.

Weight updates will take some time as testing is conducted to ensure everything works as expected. Here are final weight targets:

* Compound Borrow LINK (35% LTV): 67%
* Compound Borrow USDC (45% LTV): 30%

Current gross APY: 1.76%
Projected gross APY: 5.13%

**Comment by virendrapatidar** [comment]
@green-jeff 
Compound Borrow LINK and Compound Borrow USDC both are deployed.
Please suggest the weight.
