### ISSUE TITLE
Update AVAX weight

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#141]
Trader Joe leverage strategy earning low APY. Migrate weight to regular trader joe deposit

New weights:
* Alpha Homora: 70%
* Trader Joe: 28%

**Comment by virendrapatidar** [comment]
Ok, I am on it.

**Comment by virendrapatidar** [comment]
Trader joe leverage is set to weight 0 and rebalance is done.
Trader joe is being used for first time so will be gradul weight increase. Started with 1% and rebalanced done.

**Comment by virendrapatidar** [comment]
Trader joe weight updated to 5% and rebalanced done.

**Comment by virendrapatidar** [comment]
Updated weight to 28% and rebalance done.
