### ISSUE TITLE
Weight updated for WBTC.e (Avalanche)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#143]
Alpha Homora APY is very low. Need to move weight elsewhere while we continue to test and ramp up WBTC borrow strategies.

Suggested weight update:
* 58% TraderJoe Deposit
* 30% BenQi Leverage
* 1% TraderJoe borrow USDC
* 1% TraderJoe borrow WETH.e

**Comment by virendrapatidar** [comment]
@green-jeff - Ok, will update it accordingly.

**Comment by virendrapatidar** [comment]
@green-jeff - Weight update done as mentioned above.
