### ISSUE TITLE
Weight update for USDC.e (Avalanche)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#147]
Negative APY on TraderJoe Leverage. Pretty Low APY everywhere else. Let's split across different destinations until something good emerges:

* BenQi Deposit: 47%
* TraderJoe Deposit: 25%
* Alpha Homora: 25%

**Comment by virendrapatidar** [comment]
Keeping 1% on TraderJoe Leverage as was not able to rebalance due to loss-making. 
Others updated as mentioned.
