### ISSUE TITLE
Deploy Curve-Convex sUSD Pool to vaUSDC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#149]
Deploy Curve-Convex sUSD strategy to vaUSDC pool

Current gross APY on the strategy is 10-12%, best stablecoin yield since 1inch now routes trades through synthetix

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Can you please provide more detail on this? 
This strategy need yet to be developed (minor changes) for vaUSDC. 
I do not find details [here](https://github.com/bloqpriv/vesper-pools/blob/main/contracts/strategies/convex/4Pool)

**Comment by patidarmanoj10** [comment]
Deployment done and gradually increasing weight.
