### ISSUE TITLE
Deploy Aave Borrow USDC for vaWBTC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#152]
~Deposit ETH, Borrow USDC on Aave @ 50% LTV (50% LTV is roughly 70% of 70% maximum LTV supported)~

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 
Please confirm below. The subject mentioned vaWBTC but the description says Deposit Eth.

Deposit WBTC in vaWBTC
Borrow USDC on Aave
Deposit USDC to vaUSDC

**Comment by patidarmanoj10** [comment]
ON hold.

**Comment by patidarmanoj10** [comment]
We are not deploying any deposit eth strategy. It is on hold for time being

**Comment by patidarmanoj10** [comment]
I assume this is for vaWBTC.  #151 is for vaETH .

**Comment by patidarmanoj10** [comment]
Stale
