### ISSUE TITLE
Deploy stETH Deposit Aave Borrow USDC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#154]
Create stETH pool that utilizes the following strategy:

Deposit stETH to Aave, Borrow USDC @ 45% LTV (45% LTV is ~65% of the maximum 69% LTV)

Launch pool with 0% universal fee for meantime.

**Comment by green-jeff** [comment]
We could alternatively (and this is maybe better APY) launch stETH deposit to Maker borrow DAI

**Comment by patidarmanoj10** [comment]
Done . stEth pool launched . Presently using Aave stETH borrow DAI strategy.
