### ISSUE TITLE
Update Universal Fee on Several Pools

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#156]
Per our recent discussions, so as not to "double charge" pools that primarily feed into other Vesper pools, we need to update Universal fee on several pools:

* All Earn Pools: 0%
* vaETH: 1%
* vaWBTC: 1%

**Comment by patidarmanoj10** [comment]
@virendrapatidar Please update this.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 

Proposed multisig Nonce 84 to set universal fee to 1 % for vaETH and vaWBTC

**Comment by patidarmanoj10** [comment]
Done.
