### ISSUE TITLE
Deploy vaWBTC to Compound Leverage strategy

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#157]
Currently only 90% of WBTC TVL is deployed (Maker strategy)

Compound Leverage currently shows up-to 8% APY on WBTC. Deploy idle TVL to the leverage strategy (strategy already deployed)

New weights:
* Maker borrow DAI: 90%
* Compound Leverage: 7%

**Comment by patidarmanoj10** [comment]
Compound leverage looks okay. @virendrapatidar  set weight  to compound leverage.

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 
Set weight Compound Leverage: 7% and rebalanced.
