### ISSUE TITLE
AVAX Weight Rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#159]
BenQi Leverage yielding high APY, consistently positive APY. Move some weight from Alpha to BenQi Leverage:

* Alpha Homora: 78%
* BenQi Leverage: 20%

**Comment by patidarmanoj10** [comment]
@virendrapatidar Good to update

**Comment by patidarmanoj10** [comment]
@green-jeff Which pool?

**Comment by patidarmanoj10** [comment]
AVAX pool itself?

**Comment by green-jeff** [comment]
AVAX pool, yes :)

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 

Updated weight for vaAVAX.
Alpha Homora: 78%
BenQi Leverage: 20%
