### ISSUE TITLE
Upgrade vWBTC, vETH, vUSDC, vLINK, vDAI to v5

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#16]
v3 pending pool upgrade is a blocker to more effective rebalancing and integration of multi-strategy to the main conservative pools

**Comment by patidarmanoj10** [comment]
Work in progress. 

- [ ] vDAI
- [ ] vUNI

**Comment by virendrapatidar** [comment]
- [x] - vDAI done
- [ vLINK] in progress

We do not have vUNI (2.0). vUNI is already on 5.0.1

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 

Deployment and migration is being done as part of GH

vDAI: https://github.com/bloqpriv/vesper-pools/issues/1410
vWBTC : https://github.com/bloqpriv/vesper-pools/issues/1389
vUSDC : https://github.com/bloqpriv/vesper-pools/issues/1388
vETH : https://github.com/bloqpriv/vesper-pools/issues/1390
vLINK : https://github.com/bloqpriv/vesper-pools/issues/1392

**Comment by virendrapatidar** [comment]
Closing this as we have separate GH issue for each pool.
