### ISSUE TITLE
Avalanche WETH Weight Rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#160]
BenQi Leverage yielding good, positive APY consistently. Move some weight over - not all (don't want to push leverage strategy negative):

* BenQi Deposit: 50%
* BenQi Leverage: 47%

**Comment by patidarmanoj10** [comment]
@virendrapatidar Good to update this one

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 

Updated as below for vaWETH pool.
BenQi Deposit: 50%
BenQi Leverage: 47%
