### ISSUE TITLE
Deploy Convex FRAX-USDC Strategy to vaFRAX

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#163]
Frax Finance is undergoing migration of their liquidity from Frax4pool (where we yield currently) to a new "Frax Base Pool" of FRAX-USDC. This is the curve pool associated: https://curve.fi/fraxusdc

Strategy works like other Curve-Convex strategies: Supply LP on Curve, stake to Convex.

After deployment we can monitor and put out weight rebalance.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

I see below config for `Convex_fraxusdc_FRAX`. Should I deploy it with below config or you want any change?
Unit tests are passing with below config.

```
Convex_fraxusdc_FRAX: {
    contract: 'Convex2PlainPool',
    type: StrategyTypes.CONVEX,
    constructorArgs: {
      crvPool: Address.Curve.FRAX_USDC_POOL,
      crvSlippage: 50, // 0.5%
      masterOracle,
      swapper,
      collateralIdx: 0,
      convexPoolId: 100,
      strategyName: 'Convex_fraxusdc_FRAX',
    },
    config: { ...config },
    setup: { ...setup },
  },
```

**Comment by patidarmanoj10** [comment]
Is this fraxbp pool ?

**Comment by virendrapatidar** [comment]
No.. this is for `VAFRAX` pool. We do not have any config for fraxbp pool.

**Comment by virendrapatidar** [comment]
@green-jeff 
The mapped convex pool with LP Token "0x3175Df0976dFA876431C2E9eE6Bc45b65d3473CC" and convexPoolId: 100.
Can you please confirm if you want to deploy it?

![Convex pools for pool id 100](https://user-images.githubusercontent.com/1055074/184680663-aedfe1e8-fd91-4984-881e-5e1cb9769f3b.png)

**Comment by green-jeff** [comment]
Confirmed @virendrapatidar

**Comment by virendrapatidar** [comment]
Thanks, I will deploy it.

**Comment by virendrapatidar** [comment]
@marcelomorgado  cc @patidarmanoj10 

Unit test
```
npm test -- --scope vesper-strategies -- test/mainnet/convex/2pool/fraxusdc-frax.spec.js            
```

Deployment
```
npm run deploy -- --scope vesper-deployments -- -- --pool VAFRAX --network mainnet --target-chain mainnet --deploy-params '{"tags": "deploy-strategy", "gasprice": "20000000000"}' --strategy-name Convex_fraxusdc_FRAX
```

Release
```
npm run create-release -- --scope vesper-deployments -- -- --release 5.0.2 --pool VAFRAX --network mainnet
npm run verify -- --scope vesper-deployments -- -- --network mainnet
```

Multisign Nonce to add stragegy to vaFRAX pool : 876

Fork Testing after deployment and getting "fallbacks-failed" error from [contract](https://etherscan.io/address/0x8e4f0e00904d03b2fa805c2b07c436e7a76110bf#code) 

```
vesper-pools:   1) Mainnet Strategy sanity test
vesper-pools:        Should deposit => rebalance => withdraw:
vesper-pools:      Error: VM Exception while processing transaction: reverted with reason string 'fallbacks-failed'
vesper-pools:     at <UnrecognizedContract>.<unknown> (0x8e4f0e00904d03b2fa805c2b07c436e7a76110bf)
```

**Comment by patidarmanoj10** [comment]
This may be block number issue. plz debug

**Comment by patidarmanoj10** [comment]
cc @marcelomorgado

**Comment by virendrapatidar** [comment]
Tested it at the latest block as well getting the same error.

**Comment by virendrapatidar** [comment]
Worked after adding oracle as mentioned [here](https://github.com/bloqpriv/vesper-contracts/blob/main/vesper-commons/utils/setup.js#L213-L217)

Thanks @marcelomorgado

**Comment by virendrapatidar** [comment]
- Multisig 876 executed. 
- Added weight as 0.4%
- First, rebalance done.
- I will increase the weight to 5% tomorrow and will do one more rebalance.

**Comment by virendrapatidar** [comment]
Increased weight to 5%
added routes in swapper as rebalance was partially failing and reporting loss.

```
 VSP -> FRAX => IN
 CRV -> FRAX => IN
 CVX -> FRAX => IN
```
Last Rebalance reported profit.

**Comment by virendrapatidar** [comment]
APR with 5% weight is 7.43%
Increased weight to 27% now

**Comment by virendrapatidar** [comment]
@green-jeff cc @patidarmanoj10 

Please let me know what is the final weight for `Convex_fraxusdc_FRAX` strategy. 
I will do the last weight adjustment in one more cycle.

**Comment by virendrapatidar** [comment]
As per Zane's comment on slack, I will allocate all weight (97%) to `Convex_fraxusdc_FRAX `

**Comment by virendrapatidar** [comment]
97% of weight is allocated to Convex_fraxusdc_FRAX
