### ISSUE TITLE
Deploy Compound Borrow DAI to vaETH

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#164]
Compound Borrow DAI offers much better net borrow rates on DAI loan with much higher collateral ratios.

APY should ~double versus Maker strategy and additionally offer an extra ~40% size of loan (target 57% LTV rather than 42% on Maker)

**Comment by patidarmanoj10** [comment]
@virendrapatidar lets deploy this. Aave V2 . Deposit ETH, borrow DAI and supply to vaDAI

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Which one to deploy? The title and comments are not talking about the same.
Compound_Xy_ETH_DAI
or
AaveV2_Vesper_Xy_ETH_DAI

**Comment by patidarmanoj10** [comment]
Sorry for confusion. It should be compound. Compound_Xy_ETH_DAI

**Comment by virendrapatidar** [comment]
Deployed contract 
Multisig nonce: 871.

```
 npm run deploy -- --scope vesper-deployments -- -- --pool VAETH --network mainnet --target-chain mainnet --deploy-params '{"tags": "deploy-strategy", "gasprice": "30000000000"}' --strategy-name Compound_Xy_ETH_DAI
```

**Comment by virendrapatidar** [comment]
Testing it in fork and getting `no-routing-found`
@marcelomorgado 
Can you please provide me steps to add route and also transfer swapper ownership to bot address : 0x76d266DFD3754f090488ae12F6Bd115cD7E77eBD

**Comment by marcelomorgado** [comment]
Ownership transferred (https://etherscan.io/tx/0xe92d1c461ebf57cbbc66242b6cf893550f72876bea3486a7eb0a5fdeedd49b64)
Regarding the routes, you might want to check this function here https://github.com/bloqpriv/vesper-contracts/blob/main/vesper-commons/utils/setup.js#L81
This function is being used to prepare routes used by the tests

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Deployed : Compound_Vesper_Xy_ETH_DAI strategy for vaETH pool
Multisig nonce: 871
```
npm run deploy -- --scope vesper-deployments -- -- --pool VAETH --network mainnet --target-chain mainnet --deploy-params '{"tags": "deploy-strategy", "gasprice": "30000000000"}' --strategy-name Compound_Vesper_Xy_ETH_DAI
```

Tested it in fork and need to add only one pair in swapper

```
In:Collateral out:BorrowToken =>swapper.setDefaultRouting(swapType.EXACT_OUTPUT, tokenIn, tokenOut,.....)
```

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

- multisig executed 
- Initial weight added 8.8% and allocated 3.5 eth.
- One rebalance done.
- I will increase the weight to 9% tomorrow and will do one more rebalance.

**Comment by virendrapatidar** [comment]
One more rebalance done.

**Comment by virendrapatidar** [comment]
Weight increased to 9.5% and one more re-balance done.
