### ISSUE TITLE
Deploy Compound Borrow DAI to vaWBTC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#165]
Deposit WBTC to Compound, Borrow DAI. Lower net borrow rate and much higher collateralization than Maker loan.

This pool should increase WBTC by 2-3x and additionally offer maximum loan of ~25% more DAI (40% LTV vs 50% LTV)

**Comment by patidarmanoj10** [comment]
@virendrapatidar Lets deploy it after eth-dai is done.

**Comment by virendrapatidar** [comment]
@patidarmanoj10, sure eth-dai is deployed and tested it in fork.
I will deploy it once we do one round of testing in mainnet.

**Comment by virendrapatidar** [comment]
Deployed Compound_Vesper_Xy_WBTC_DAI for vaWBTC pool.
Multisig nonce : 872

**Run Unit Test**
```
npm test -- --scope vesper-strategies -- test/mainnet/compound/xy/vesper/vawbtc.spec.js
```

**Deployment**
```
npm run deploy -- --scope vesper-deployments -- -- --pool VAWBTC --network mainnet --target-chain mainnet --deploy-params '{"tags": "deploy-strategy", "gasprice": "30000000000"}' --strategy-name Compound_Vesper_Xy_WBTC_DAI
```

**Create release**
```
npm run create-release -- --scope vesper-deployments -- -- --release 5.0.2 --pool VAWBTC --network mainnet
```

**Added Routes in swapper.**
```
#1 WBTC -> DAI => OUT
#2 DAI -> WBTC => IN
#3 VSP -> WBTC => IN
```

Tested deployed strategy in fork with 0.2% weight.

**Comment by virendrapatidar** [comment]
- Multisig nonce : 872 executed
- Added 0.1% weight
- Did the first [rebalance](https://etherscan.io/tx/0x850d7593d8ddaab9d71673a522e8d4ccc0b711febd869f8cd52c3e2d4a5123c0) and it deployed ~5K USD.

**Comment by virendrapatidar** [comment]
- Did one more rebalance with 0.2% weight. Found the issue in swapping COMP to WBTC.
- Fixed the COMP => WTBC => IN routing issue.
- Increased weight is 0.4%
- Did another rebalance and now all looking okay.
