### ISSUE TITLE
ETH Weight Updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#166]
Aave ETH deposit APY is very good. Compound DAI borrow APY is also quite competitive. Maker DAO is competitive and consistent.

Let's split weight among each for time being:

Aave deposit ETH borrow DAI: 50%
Maker deposit ETH borrow DAI: 27%
Compound deposit ETH borrow DAI: 20%

**Comment by virendrapatidar** [comment]
@green-jeff 

First round updated weight as below (just reduced 10% for Maker and given 5% each to aave and compound).
Aave deposit ETH borrow DAI: 6% (old weight 1%)
Maker deposit ETH borrow DAI: 77% (old weight 87%)
Compound deposit ETH borrow DAI: 16% (old weight 11%)

In the next round, I will reduce maker weight by another 25%.

**Comment by virendrapatidar** [comment]
Updated weight as below.
Aave deposit ETH borrow DAI: 31% (old weight 6%)
Maker deposit ETH borrow DAI: 52% (old weight 77%)
Compound deposit ETH borrow DAI: 16% (old weight 16%) - no change.

**Comment by virendrapatidar** [comment]
The final weight update was done as below.
Aave deposit ETH borrow DAI: 50%
Maker deposit ETH borrow DAI: 27%
Compound deposit ETH borrow DAI: 20%
