### ISSUE TITLE
Exit Compound Leverage on vaLINK

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#169]
Compound no longer paying rewards to LINK market. Exit Compound Leverage strategy (which is now severely lossmaking).

Migrate all weight to: Aave deposit, Borrow USDC

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 

We do not have Aave deposit, Borrow USDC deployed for vaLINK. 
This will be a new deployment, + seed test, and not just a weight update.

**Comment by patidarmanoj10** [comment]
@virendrapatidar Lets set 0 weight to existing before deploy new strategy.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 - Okay.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Tested first in the fork, rebalance is failing on setting the weight to 0 due to loss-making.
It has worked with 14 weights which is 0.14%.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

The new strategy to be deployed would be Aave deposit, Borrow USDC, and supply borrowed USDC to vaUSDC pool?

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
PR Raised and UT passing for _vaLINK_ pool, _AaveV2_Vesper_Xy_LINK_USDC_ stragegy.

**Comment by virendrapatidar** [comment]
Proposed Nonce 898 to add AaveV2_Vesper_Xy_LINK_USDC strategy for vaLINK pool

**Comment by virendrapatidar** [comment]
Added routes in swapper

#1 LINK -> USDC => OUT
#2 USDC -> LINK => IN
#3 VSP -> LINK => IN
#4 AAVE -> LINK => IN

**Comment by virendrapatidar** [comment]
- Tested it in fork
- Set weight 2%, Deposit, rebalance, withdraw, rebalance, deposit, deposit, Weight 0, rebalance.

**Comment by virendrapatidar** [comment]
- 898 executed and strategy got added for vaLINK pool
- First, rebalance called with 5% weight. The next one would be with 25% and then with 95%.

**Comment by virendrapatidar** [comment]
Allocated weight 25%, and then 96%.
All rebalances result in profit.

**Comment by virendrapatidar** [comment]
Rebalance fails if we set 0 weight for Compound Leverage. Keeping it 0.14% for now.
