### ISSUE TITLE
AVAX weight update

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#170]
BenQi Lev is low APY. Migrate weight to:

* Alpha Homora: 78%
* BenQi Deposit: 20%

**Comment by patidarmanoj10** [comment]
Update weight . Check this strategy already in mainnet and tested/used in past.

**Comment by virendrapatidar** [comment]
@green-jeff - We do not have the BenQi Deposit strategy deployed for the vaAVAX pool.
Do you want to deploy BenQi Deposit strategy or we can give weight to TraderJoe deposit or aave deposit?

**Comment by green-jeff** [comment]
@virendrapatidar Let's just send all weight to Alpha Homora for meantime

**Comment by virendrapatidar** [comment]
Allocated Alpha Homora: 98% and called rebalance.
