### ISSUE TITLE
Avalanche WETH weight Update

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#171]
BenQi Leverage is loss making. Migrate weight as follows:

* BenQi Deposit: 77%
* Alpha Homora: 20%

**Comment by virendrapatidar** [comment]
- Alpha Homora was used in past.
- No change is needed for BenQi Deposit. It is already having 77% weight.
- Moved BenQi Leverage 20% weight to Alpha Homora.
- Rebalanced and fund deployed to Alpha Homora.
