### ISSUE TITLE
Avax WBTC Weight Update

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#172]
No more APY on TraderJoe. Migrate WBTC weight as follows:

* 97% Alpha Homora

**Comment by patidarmanoj10** [comment]
Update weight . Check this strategy already in mainnet and tested/used in past.

**Comment by virendrapatidar** [comment]
Yes, it is being used with 10% weight for 4 months now. 
Moving all weight to Alpha Homora.

**Comment by virendrapatidar** [comment]
- 97% of weight is allocated to Alpha Homora
- rebalanced and deployed funds to Alpha Homora.
