### ISSUE TITLE
Update minBorrowRatio and maxBorrowRatio in leverage strategies.

### ISSUE THREAD

**Issue by patidarmanoj10** [vesperfi/vesper-pool-ops#173]
All leverage strategies deposit and borrow same assets hence there is no risk of Marker price changes.  To get max yield in leverage update borrow configuration in all leverage strategies.

minBorrowRatio: 88
maxBorrowRatio: 95

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

As discussed, we can't use the above limit. Tested it in the fork and the max I can use is 79% for the vaDAI leverage strategy.

Upating it as updateBorrowRatio(7300, 7900)

**Comment by virendrapatidar** [comment]
Tested in fork with 
minBorrowRatio: 73
maxBorrowRatio: 77.

**Comment by virendrapatidar** [comment]
Proposed nonce 913 to update borrow ratio as below for vaDAI compound leverage straegy.
minBorrowRatio: 7300
maxBorrowRatio: 7700

**Comment by green-jeff** [comment]
@virendrapatidar @patidarmanoj10 Is that 73-77% collateral rate of 73-77% of max allowed CR by Compound? meaning 73-77% or (73-77%)*84% = 62-65%

I think if we do 62-65% CR only, this strategy is not as competitive as Curve-Convex

**Comment by patidarmanoj10** [comment]
@green-jeff Sorry for confusion.  This is absolute value not % of CF of protocol.  Compound leverage is set with new params.

**Comment by virendrapatidar** [comment]
Multisig nonce 913 executed.
