### ISSUE TITLE
vaETH Rebalance - preparing for large deposit

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#174]
Metronome DAO will deposit 1,000 ETH over coming days into ETH-DAI pool. 

Currently, ETH weight is as follows:
* 50% Aave-Borrow-DAI
* 47% Compound-Borrow-DAI
* 3% Pool Buffer

Would like to change weights on receipt of influx of ETH without causing unnecessary rebalances: Idea is to keep the ETH in Compound that's currently there without allocating more weight or removing ETH that's already there. 

Currently, the 47% of ~450 ETH deposited to Compound is 211 ETH. After new 1,000 ETH deposit, 211 ETH = ~15% of pool TVL.

Looking to add majority of ETH to Aave strategy and some amount of ETH on deposit to Alpha Homora. The new weights look as follows:
* 62% Aave-Borrow-DAI
* 20% Deposit to Alpha Homora
* 15% Compound-Borrow-DAI
* 3% Pool Buffer

**Comment by green-jeff** [comment]
Note that once audits return, there are several high APY ETH strategies that will unlock:

* Stargate LP: 6%+ currently
* Euler Borrow DAI/USDC - 3-5% APY
* Compound V3 Borrow USDC - 4-6% APY

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
Requested to add bot address as delegator for metronome multi-sig. 
 - Metronome multi-sig address?
 - How much amount to transfer to vaETH pool so I can prepare multi-sig transfer txn.

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 

The calculation is [here](https://docs.google.com/spreadsheets/d/1Q3FfqV0k052ZcwB929ztsyAEJ0087tWZcNdgd7M3nag/edit#gid=879281881)

The rebalance is done accordingly. vaETH now has 3 % eth left in the pool.

61% Aave-Borrow-DAI
20% Deposit to Alpha Homora
15% Compound-Borrow-DAI
3% Pool Buffer
