### ISSUE TITLE
vaDAI prep for deposit

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#175]
Per #174 - Deposit of roughly 500,000 DAI expected to vaDAI pool.

Currently, available DAI is split ~50/50 between Convex sUSD 4pool and Compound Leverage Strategies.

Send all new DAI after deposit to the Convex sUSD 4pool, no more additional TVL to Compound Leverage

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 
Calculation [here](https://docs.google.com/spreadsheets/d/1Q3FfqV0k052ZcwB929ztsyAEJ0087tWZcNdgd7M3nag/edit#gid=0)

All new fund (505K DAI) deployed to Convex sUSD 4pool strategy.
