### ISSUE TITLE
Migrate WETH.e Weight to TraderJoe Deposit

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#181]
Whale took out massive borrow of WETH.e on Trader Joe. Move ETH to capture APY:

* TraderJoe Deposit: 97%
* Pool Buffer: 3%

**Comment by virendrapatidar** [comment]
Rebalance transactions : https://snowtrace.io/address/0xC00fAe34553dbF360Dc8E2a90fd25b4BbBD3977f

**Comment by virendrapatidar** [comment]
ok, it worked with increased weight.
As of now allocated 48% of weight. I will do the final desired update tomorrow.

**Comment by virendrapatidar** [comment]
Weight updated and rebalance done.
