### ISSUE TITLE
Migrate vaDAI Convex Strategy

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#184]
Synthetix sUSD Curve-Convex Pool had rewards cut recently, APY is very low (avg 2.5%). DOLA is highest APY safe stablecoin on Curve-Convex @ 9% APY.

Migrate half of sUSD weight to new DOLA-3pool Convex deposit

This will require a new strategy deployment.

Weight update should be as follows:

* Compound Leverage: 44% (unchanged)
* Curve-Convex Synthetix sUSD: 23%
* Curve-Convex DOLA-3pool: 23% 

If DOLA performs well, we will look to move weight off of sUSD altogether

**Comment by patidarmanoj10** [comment]
@virendrapatidar  Can you simulate , what is slippage loss in withdrawing half from sUSD curve pool.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

I am testing it in fork. Reduced weight of Curve-Convex Synthetic to half but rebalance is failing.
Not able to simulate rebalance in fork.

```
vesper-pools:   Mainnet Strategy sanity test
vesper-pools: price per share 1071316342935067475
vesper-pools: poolName  vaDAI Pool
vesper-pools: strategyName  Convex-SUSD4Pool-DAI
vesper-pools: availableCreditLimit 396882735317948490197
vesper-pools: current debtRatio 5644
vesper-pools: Total Strategy debt 1393130316749202573999980
vesper-pools: new debtRatio 2822
vesper-pools: availableCreditLimit 0
vesper-pools:     1) Should Test strategy
vesper-pools:   0 passing (22s)
vesper-pools:   1 failing
vesper-pools:   1) Mainnet Strategy sanity test
vesper-pools:        Should Test strategy:
vesper-pools:      Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="rebalance()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
```

**Comment by virendrapatidar** [comment]
ok.. wait.. this strategy is old and rebalance function do not return profit, loss, payback in response.

**Comment by virendrapatidar** [comment]
@green-jeff , @patidarmanoj10 

Do we need to deploy DOLA below convex pool (Curve-Convex DOLA-3pool)?

![DOLA](https://user-images.githubusercontent.com/1055074/196234462-f01451b4-9f53-4a5f-9eca-cc43f08c4dd2.png)

**Comment by green-jeff** [comment]
@virendrapatidar Yessir. With the same parameters outlined in original post

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
Curve Convex DATA straegy deployed for vaDAI pool.
Multisig nonce 920

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Please confirm how we want to update the weight. 
We already using weight of approx 99% for vaDAI.
Should I gradually reduce the weight for Curve-Convex Synthetix sUSD and increase for Curve-Convex DOLA-3pool

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Please confirm how we want to update the weight. 
We already using weight of approx 99% for vaDAI.
Should I gradually reduce the weight for Curve-Convex Synthetix sUSD and increase for Curve-Convex DOLA-3pool

**Comment by patidarmanoj10** [comment]
Increase gradually. Please set small weight and then rebalance atleast 2 times

**Comment by virendrapatidar** [comment]
ok

**Comment by virendrapatidar** [comment]
- Initial weight 2.5% assigned. 
- First [rebalance](https://etherscan.io/tx/0x4ace071e83a2a3a12733886fa3dacb9cf7f1e6059a18bb7baabf547429fd4fd2) done 
- I will call rebalance again in few hours to check the APR.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Second [rebalance](https://etherscan.io/tx/0x848dc2181ad0c45b60536df5499c23b5da881d74a54ffa304b48c093aaf88e62#eventlog) reported loss

```
profit :0
loss :10318007992707708333
payback :0
strategyDebt :17339729230784901985749
poolDebt :2449183710496597321279530
creditLine :464310359671846875
```

**Comment by virendrapatidar** [comment]
The [second rebalance ](https://ethtx.info/mainnet/0x848dc2181ad0c45b60536df5499c23b5da881d74a54ffa304b48c093aaf88e62/)was showing an orange icon on etherscan. 
Added below default route in swapper.

CRV -> DAI => IN
CVX -> DAI => IN

**Comment by patidarmanoj10** [comment]
This is routing issue.  It seems CVX DAI route is wrong.

**Comment by virendrapatidar** [comment]
Rebalance is okay now and not reporting any issue

**Comment by virendrapatidar** [comment]
Weight updated as below and rebalance called.
Curve-Convex Synthetix sUSD: 30%
Curve-Convex DOLA-3pool: 26%

**Comment by virendrapatidar** [comment]
@patidarmanoj10 - Should we move all weight from Curve-Convex Synthetix and move to Curve-Convex DOLA-3pool?

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
OK, I will change 10% in each iteration.

**Comment by virendrapatidar** [comment]
- Reduced weight of Curve-Convex Synthetix sUSD to 20% and rebalance done
- Increased weight of Curve-Convex DOLA-3pool to 36% and rebalance done

**Comment by patidarmanoj10** [comment]
How is dola strategy doing? what is actual APY we getting in DOLA? Just curios to know is it yielding good for us.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
vaDAI APR for DOLA strategy. We are increasing weight on each rebalance so APR calculation is not that  accurate here.

![apr](https://user-images.githubusercontent.com/1055074/198090648-bf37af7d-4bef-4224-9dd3-bbe447adecf0.png)

**Comment by virendrapatidar** [comment]
Closing it as @green-jeff do not want to increase weight for Dola any more. [Ref](https://bloqinc.slack.com/archives/CMNT47A5V/p1666903423043799)
