### ISSUE TITLE
Migrate DAI Weight to Compound Leverage

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#185]
DOLA pool is migrating rewards and TVL to FraxBP. Peg has been strong, let's pull out over time back into Compound Leverage, which is easy to enter into/exit out of with no slippage:

Updated Weights:
* Convex sUSD: 20% (unchanged)
* Compound Leverage: 80%

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
Set the weight to 0 for Dola strategy but not able to rebalance. 
**error: execution reverted: price-invalid**


```
warn: Error in sendTransaction transaction, operation: rebalance, pool: vaDAI, toAddress: 0x269041586AB615Cd19E8CbFABC7C45CdA8179289, nonce: 6871, error: execution reverted: price-invalid

```

**Comment by virendrapatidar** [comment]
This is due to new chainlink oracle : 0x0C102819074dA01f30360676F36b86c8be68A3E7
Need to update stale period.

**Comment by virendrapatidar** [comment]
Weight updated as mentioned and rebalance called.
