### ISSUE TITLE
Deploy Convex for Frax strategy to vaUSDC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#187]
With audits returning on Convex for Frax strategy set, deploy Convex for Frax FraxBP (FRAX-USDC) strategy to USDC pool.

**Comment by green-jeff** [comment]
If strategy is OK, we should look to migrate all weight (45% of total pool) from existing Convex FraxBP strategy to the Convex for Frax strategy

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @rokso 
Need to discuss this a bit. I will ping you on slack.

**Comment by virendrapatidar** [comment]
Nonce 936: Deployed Convex For Frax Strategy for vaUSDC
