### ISSUE TITLE
Deploy Convex for Frax strategy for vaFRAX

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#188]
With audits back on Convex for Frax, deploy Convex for Frax FraxBP (FRAX-USDC) strategy to vaFRAX

**Comment by green-jeff** [comment]
Once deployment is complete, migrate all weight in the pool from previous Convex FraxBP strategy to new one

**Comment by virendrapatidar** [comment]
https://frax.convexfinance.com/
"Convex:FRAX/USDC"

LP token address	0x8a53ee42FB458D4897e15cc7dEa3F75D0F1c3475
Curve LP token address	0x3175Df0976dFA876431C2E9eE6Bc45b65d3473CC
Staking address	0x963f487796d54d2f27bA6F3Fbe91154cA103b199

**Comment by virendrapatidar** [comment]
I am preparing configuration Convex for Frax FraxBP (FRAX-USDC) strategy to vaFRAX
I have got the curve pool but looking at the coin index which should be our collateral token. But I do not get the correct coin as collateral token.

here is the config I am preparing.  `convexPoolId` and `crvPool` is correct here. Having issues in finding `collateralIdx`

```
ConvexForFrax_fraxdola_FRAX: {
    contract: 'ConvexForFrax',
    type: StrategyTypes.CONVEX_FOR_FRAX,
    constructorArgs: {
      crvPool: Address.Curve.FRAX_DOLA_POOL, // 0xE57180685E3348589E9521aa53Af0BCD497E884d
      curvePoolType: CurvePoolTypes.PLAIN_2_POOL,
      depositZap: ethers.constants.AddressZero,
      crvToken: Address.Curve.CRV,
      crvSlippage: 100, // 1%
      masterOracle,
      swapper,
      collateralIdx: 0, // TODO crvPool has 2 coins but none of them is FRAX.
      convexPoolId: 27, // THis is pool id from convex registry.
      strategyName: 'ConvexForFrax_fraxusdc_FRAX',
    },
    config: { ...config },
    setup: { ...setup },
  },
```

At coin index 0 it has `DOLA` `0x865377367054516e17014CcdED1e7d814EDC9ce4`
and at coins index 1 it has `crvFRAX` `0x3175Df0976dFA876431C2E9eE6Bc45b65d3473CC`

**Comment by virendrapatidar** [comment]
Nonce 935: Deployed Convex For Frax Strategy for vaFRAX
