### ISSUE TITLE
Deploy Euler Borrow Strategy to vaETH

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#189]
With audits coming back for Euler, deploy Euler borrow DAI strategy to vaETH pool

**Comment by patidarmanoj10** [comment]
Pool: vaETH
Strategy: Euler strategy. Deposit ETH , borrow DAI and deposit to vaDAI

**Comment by virendrapatidar** [comment]
Deployed nonce 929

**Comment by virendrapatidar** [comment]
I have wrongly deployed Euler Deposit strategy instead of Euler Borrow. Nonce 929 needs to be rejected.

**Comment by virendrapatidar** [comment]
Nonce 929 resubmitted to deploy Euler Borrow stragegy for vaETH pool.

**Comment by virendrapatidar** [comment]
Nonce 929 executed.
