### ISSUE TITLE
Deploy Convex for Frax (DOLA) Strategy to vaUSDC pool

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#192]
Deploy Convex for Frax strategy DOLA-FraxBP to vaUSDC Pool

**Comment by virendrapatidar** [comment]
https://frax.convexfinance.com/
"Convex:DOLA/FRAXBP"

LP token address	0xF06c8696730cf760619e4fA0eDd0f79ea50531A9
Curve LP token address	0xE57180685E3348589E9521aa53Af0BCD497E884d
Staking address	0xE7211E87D60177575846936F2123b5FA6f0ce8Ab

**Comment by virendrapatidar** [comment]
Nonce 938: Deployed Convex For Frax Strategy (dolafraxbp) for vaUSDC pool.

**Comment by virendrapatidar** [comment]
executed Nonce 938: Deployed Convex For Frax Strategy (dolafraxbp) for vaUSDC pool.

**Comment by virendrapatidar** [comment]
This strategy is mistakenly deployed from the wrong branch `main` branch. It should have been deployed from `ConvexForFrax_fraxdolabp` branch

**Comment by virendrapatidar** [comment]
Nonce 941: Deployed Convex For Frax Strategy (dolafraxbp) for vaUSDC pool.
