### ISSUE TITLE
Deploy Convex for Frax (DOLA) Strategy to vaFRAX pool

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#193]
Deploy Convex for Frax DOLA-FraxBP strategy for vaFRAX pool

**Comment by virendrapatidar** [comment]
https://frax.convexfinance.com/
"Convex:DOLA/FRAXBP"

LP token address	0xF06c8696730cf760619e4fA0eDd0f79ea50531A9
Curve LP token address	0xE57180685E3348589E9521aa53Af0BCD497E884d
Staking address	0xE7211E87D60177575846936F2123b5FA6f0ce8Ab

**Comment by virendrapatidar** [comment]
Nonce 937: Deployed Convex For Frax Strategy (dolafraxbp) for vaFRAX pool.

**Comment by virendrapatidar** [comment]
executed Nonce 937: Deployed Convex For Frax Strategy (dolafraxbp) for vaFRAX pool.

**Comment by virendrapatidar** [comment]
This strategy is mistakenly deployed from the wrong branch `main` branch. It should have been deployed from `ConvexForFrax_fraxdolabp` branch

**Comment by patidarmanoj10** [comment]
We should always deploy from main . If a PR is suppose to merge then wait for merge

**Comment by virendrapatidar** [comment]
Nonce 940: Deployed Convex For Frax Strategy (dolafraxbp) for vaFRAX pool.
