### ISSUE TITLE
Deploy Compound v2 Borrow USDC to vaDAI pool

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#194]
Deploy Compound v2 deposit DAI, borrow USDC strategy to vaDAI pool

This strategy protects DAI yield if we are not able to get good yield on DAI pool. Best yield currently is Stargate, Convex for Frax which DAI has no access to.

**Comment by patidarmanoj10** [comment]
Pool: vaDAI
Strategy: deposit DAI borrow USDC, deposit usdc to vaUSDC.
