### ISSUE TITLE
Deploy Euler Borrow USDC strategy to vaDAI pool

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#195]
Deploy deposit DAI, Borrow USDC to vaDAI pool.

This helps protect yield on DAI in case of no new yield opportunities. USDC has better yield opportunity with Stargate and Convex for Frax, which DAI has no access to.

**Comment by patidarmanoj10** [comment]
Pool: vaDAI. 
strategy: despoti DAI to Euler, borrow USDC, deposit USDC to vaUSDC.

**Comment by virendrapatidar** [comment]
Nonce 930: Deployed Euler Borrow USDC strategy to vaDAI pool
Multisig executed.
