### ISSUE TITLE
Migrate vaUSDC Weight (new strategies)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#196]
Pending #192 #187 

Migrate vaUSDC weight as follows:

* Convex for Frax FraxBP: 35%
* Stargate: 35%
* Convex for Frax DOLA: 25%

Migrate weight out of existing FraxBP strategy before Synthetix strategy.

Migrate weight into DOLA strategy only when price is favorable (DOLA is trading below $1). Migrate into other strategies first if necessary.

**Comment by green-jeff** [comment]
We must be careful about how much weight in Convex for Frax strategies that require 7 day lockup. New weight proposition:

Convex sUSD: 50%
Stargate: 25%
Convex for Frax DOLA: 22%
Pool Buffer: 3%

**Comment by virendrapatidar** [comment]
Convex for Frax FraxBP - added 2 % weight for first rebalance. 
In the last comments, it was not listed so I will remove it after a couple of rebalances testing.

**Comment by virendrapatidar** [comment]
Stargate: 25% weight set and called rebalance.

**Comment by virendrapatidar** [comment]
2% weight set for Convex for Frax DOLA and called rebalance.

**Comment by virendrapatidar** [comment]
Added default route for CSV and CRV using uniswapV2.
FXS is another reward token but do not find any liquidity for this on UniV2 and Sushi.

**Comment by green-jeff** [comment]
@virendrapatidar 

Let's put excess USDC into Stargate while we are ramping up DOLA strategy:

Convex sUSD: 50%
Convex for Frax DOLA: 5%
Stargate: 40%

then

Convex sUSD: 50%
Convex for Frax DOLA: 25%
Stargate: 20%

USDC pool is lower TVL so should not be an issue to temporarily put more weight into Stargate

**Comment by virendrapatidar** [comment]
Convex for Frax DOLA with 5% - Rebalance done and resulting into profit.

**Comment by patidarmanoj10** [comment]
Go ahead and increase to 15%.

**Comment by virendrapatidar** [comment]
The suggested final weight. I will do adjustments one day before lockin period expire.

```
Convex sUSD: 50%
Convex for Frax DOLA: 25%
Stargate: 20%


```

**Comment by virendrapatidar** [comment]
@rokso 
As per our discussion, we will not be increasing any more weight on Convex for Frax DOLA. I will stop rebalancing this strategy so we won't have a new lock-in period. 
Next week, we will deploy a new strategy and Fund will be withdrawn from Convex for Frax DOLA.

**Comment by rokso** [comment]
That's correct. Closing this in favor of #208.
