### ISSUE TITLE
Migrate vaFRAX Weight (new strategies)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#197]
Pending #188 #193 

Migrate FRAX Weight as follows:

* Convex for Frax FraxBP A: 35%
* Convex for Frax FraxBP B: 35%
* Convex for Frax DOLA: 28%

We are using two identical strategies due to 1 day lockup of funds associated with these strategies.

**Comment by patidarmanoj10** [comment]
We dont need to do FraxBP A and B.  We will done of two and DOLA .

**Comment by green-jeff** [comment]
We have two more strategies for Frax as well potentially: Stargate and Convex for Frax "Aave FRAX"

Convex AaveFrax: 35%
FraxBP: 30%
DOLA: 23%
Stargate: 10%
Pool Buffer: 2%

**Comment by green-jeff** [comment]
@patidarmanoj10 

Let's just do DOLA for now on the Frax side of Convex. 

FraxBP (Regular Convex): 60%
DOLA (Convex for FRAX): 23%
Stargate: 15%
Pool Buffer: 2%

**Comment by virendrapatidar** [comment]
Added 0.4% weight to Startgate and called first rebalance.

**Comment by virendrapatidar** [comment]
Default route added for STG and FRAX.

**Comment by virendrapatidar** [comment]
Initially, I added a default route for STG to FRAX using uniswap V2 but rebalance still [failing](https://dashboard.tenderly.co/tx/mainnet/0x0579109c553999175bb3b6cb4b77bca522c75d091cea712e1b8dac491339cb7e?trace=0.1.2.2.0.3
) in swap even when I can see uniswapV2 UI gives conversion.

![uniswapv2](https://user-images.githubusercontent.com/1055074/205313365-60056c59-787a-4b90-989e-306fbd6f4252.png)

Tested swap using the default route in the fork is failing with uniswapV2.

Then I change the  STG to FRAX using sushiswap. Tested it in fork and it worked.
![sushi](https://user-images.githubusercontent.com/1055074/205313824-3d012ac8-14f6-4315-b237-277912b7735b.png)

However rebalance is [failing](https://dashboard.tenderly.co/virendrapatidar/project/simulator/26f4be08-6b05-4c12-8d3c-6ab2841b2fab?trace=0.6.1.0) 
Error `error: execution reverted: Stargate: not enough lp to redeem`

**Comment by virendrapatidar** [comment]
The above issue was due to very small collateral amount was converted into 0 LP token. This is fixed in smart contract.
Multisig txn : 944 to migrate Stargate strategy for vaFRAX pool to new stargate strategy.

**Comment by virendrapatidar** [comment]
944 executed and strategy is migrated.

**Comment by virendrapatidar** [comment]
Added default route for CSV using uniswapV2.
CRV and FXS are failing on UniV2 and Sushi.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
As mentioned in ticket, I will gradually increase weight for below strategies

DOLA (Convex for FRAX): 23%
Stargate: 15%

As of now both has 0.4% weight allocated.

**Comment by virendrapatidar** [comment]
Updated the weight of stargate to 5% and rebalanced. Rebalance shows small profit and 4% APR.

Profit : 0.595772168435721901, APR : 4.02%, Date: "Tue, 06 Dec 2022 02:55:47 GMT"
Profit : 0.218245036024118687, APR : 4.64%, Date: "Mon, 05 Dec 2022 12:16:59 GMT"

**Comment by green-jeff** [comment]
@virendrapatidar 

Gradual weight updates:

Convex FraxUSDC: 78% 
Convex for Frax DOLA: 5%
Stargate: 15%

Convex FraxUSDC: 60%
Convex for Frax DOLA: 23%
Stargate: 15%

**Comment by virendrapatidar** [comment]
Convex for Frax DOLA: 5% is set. Next rebalance will be called after 6 days.
Stargate as of now set to 5%, We have done a couple of rebalances in the last 24 hours. Would wait for 1 day before increasing weight further.

**Comment by virendrapatidar** [comment]
Convex FraxUSDC: 78% - rebalance done.
Stargate: 15% -  rebalance done.

**Comment by virendrapatidar** [comment]
Convex for Frax DOLA: 5% weight rebalance done and resulting in to profit.

**Comment by patidarmanoj10** [comment]
May be you can do 15 or 20% if all looks okay.

**Comment by virendrapatidar** [comment]
Below is the suggested final weights.

Convex FraxUSDC: 60%
Convex for Frax DOLA: 23%
Stargate: 15%

**Comment by virendrapatidar** [comment]
@rokso 
As per our discussion, we will not be increasing any more weight on Convex for Frax DOLA. I will stop rebalancing this strategy so we won't have a new lock-in period. 
Next week, we will deploy new strategy and Fund will be withdraw from Convex for Frax DOLA.

**Comment by rokso** [comment]
closing this in favor of #209
