### ISSUE TITLE
Migrate vaETH weight (new strategies)

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#198]
Pending #189 #191 

Migrate ETH weight as follows:
* Euler Borrow DAI: 77%
* Stargate: 20%

Note that Alpha Homora strategy is only semi-liquid. Withdraw from Alpha when available, otherwise withdraw from other strategies.

**Comment by virendrapatidar** [comment]
- Withdraw from Alpha Hamora
- Given 2% weight to Euler Borrow and Stargate
- Rebalance done.

**Comment by virendrapatidar** [comment]
Second rebalance done
allocated 8% weight to both Euler Borrow and Stargate

**Comment by virendrapatidar** [comment]
Default route for stargate reward token (STG) 0xAf5191B0De278C7286d6C7CC6ab6BB8A73bA2Cd6 was missing.
Added the route. Next reblance should not show yellow icon (partial failure on etherscan)

**Comment by virendrapatidar** [comment]
Stargate 20% weight is set and called rebalance.

**Comment by virendrapatidar** [comment]
Euler Borrow DAI: 37% weight is set and rebalance is done.

**Comment by virendrapatidar** [comment]
Euler Borrow DAI: 77% is set and rebalanced.
