### ISSUE TITLE
Migrate vaAVAX Weight to BenQi

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#199]
Migrate all weight to BenQi Deposit:

* BenQi Deposit: 98%
* Pool Buffer: 2%

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 

We only have Benqi leverage strategy deployed for vaAVAX pool. Do not have Benqi deposit deployed yet.
Do you want to deploy BenQi Deposit and then update the weight?

**Comment by patidarmanoj10** [comment]
yes

**Comment by virendrapatidar** [comment]
First weight update to 5% and rebalance done.

**Comment by virendrapatidar** [comment]
Default route was missing for rewards => collateral token. Added default route.
