### ISSUE TITLE
Deploy Aave v3 Borrow DAI Strategy to vaAVAX

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#201]
Deploy following Strategy to Aave v3 on Avalanche for vaAVAX pool:

Deposit AVAX to Aave ==> Borrow DAI ==> Deposit DAI to vaDAI pool

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

The `AaveV3VesperXy.sol` is not ready for Native token as collateral. 
I created a deployment config as part of PR https://github.com/bloqpriv/vesper-contracts/pull/350 but tests are failing.

```
vesper-strategies:        "before each" hook for "Should allow gasless approval using permit()":
vesper-strategies:      Error: VM Exception while processing transaction: reverted with reason string 'SafeERC20: approve from non-zero to non-zero allowance'
```

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

The `AaveV3VesperXy.sol` is not ready for Native token as collateral. 
I created a deployment config as part of PR https://github.com/bloqpriv/vesper-contracts/pull/350 but tests are failing.

```
vesper-strategies:        "before each" hook for "Should allow gasless approval using permit()":
vesper-strategies:      Error: VM Exception while processing transaction: reverted with reason string 'SafeERC20: approve from non-zero to non-zero allowance'
```

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @rokso 
Couple of unit test failing due to error from AaveV3. 
More details on PR [here](https://github.com/bloqpriv/vesper-contracts/pull/350#issue-1451460449)
