### ISSUE TITLE
Migrate Avax USDC.n Weight

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#202]
Pending #200 

Migrate all USDC.n weight on Avalanche to Stargate:

Stargate: 97%
Pool Buffer: 3%

**Comment by virendrapatidar** [comment]
First weight update done 15% and rebalanced.

**Comment by virendrapatidar** [comment]
Rebalance was partially failing, Added default routing.

**Comment by virendrapatidar** [comment]
Weight updated.
