### ISSUE TITLE
Deploy AaveFRAX Strategy on Convex for Frax

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#203]
Convex for Frax has a gauge for AaveFRAX deposits. This is high yield pool with minimal risk - good FXS payout + underlying Aave APY. Lockup is only 1 day instead of 7.

Strategy works as follows:
Deposit FRAX to Aave -> Receive aFRAX -> Lock in Convex AaveFrax for minimum 1 day lockup

**Comment by patidarmanoj10** [comment]
Not significant rewards and apy lately so closing this.
