### ISSUE TITLE
vaETH Weight Updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#204]
Euler Borrow DAI no longer profitable. Let's migrate loan back to Aave while there is a large pool buffer for DAI.

New weight:
* Aave Borrow DAI: 77%
* Stargate: 20%

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
Can you please confirm, when I should do this change?

**Comment by rokso** [comment]
@virendrapatidar It can be done at anytime IMO but as vaDAI has DAI sitting in pool it will be easy withdraw from EulerBorrowDAI of vaETH. Do think there will be any issue in doing this change?

**Comment by virendrapatidar** [comment]
- I have tested it in fork and it's failing there as well.
- Tried to do rebalance of both vaDAI strategies and claimAndSwapRewards before calling rebalance of Aave Borrow DAI strategy of vaETH but still failing.
- Rebalance worked after donating 20vaDAI.
