### ISSUE TITLE
Deploy Curve-Convex FraxBP-DOLA Strategy to vaUSDC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#206]
Deploy new Curve-Convex FraxBP-DOLA strategy to vaUSDC pool. Note that this is different from the Convex for Frax strategy and does not require a lockup.

- [x] Prepare deployment config
- [x] Run tests in the fork for migration or add new strategy.
- [x] Deployment on mainnet.
- [x] Multisig transaction signing
- [x] Multisig transaction execution
- [ ] Sanity tests in fork before updating weight.
- [ ] Gradual weight update
- [ ] Multiple Rebalances

**Comment by virendrapatidar** [comment]
@rokso 

Can you please confirm if we need to deploy this configuration? 
https://github.com/bloqpriv/vesper-contracts/blob/main/vesper-commons/config/mainnet/strategyConfig.js#L1237

**Comment by virendrapatidar** [comment]
Closing this as we will update as part of https://github.com/vesperfi/vesper-pool-ops/issues/212
