### ISSUE TITLE
Deploy Curve-Convex FraxBP-DOLA Strategy to vaFRAX

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#207]
Deploy new Curve-Convex FraxBP-DOLA strategy to vaFRAX pool. Note that this is different from the Convex for Frax strategy and does not require a lockup.

- [x] Prepare deployment config
- [x] Run tests in the fork for migration or add new strategy.
- [x] Deployment on mainnet.
- [x] Multisig transaction signing
- [x] Multisig transaction execution

**Comment by virendrapatidar** [comment]
Deployed and added in pool.
Weight update will be done as part of https://github.com/vesperfi/vesper-pool-ops/issues/213
