### ISSUE TITLE
New Weight updates for vaUSDC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#210]
Understanding that any new strategy deployments may be delayed through the new year, looking to optimize weight across existing strategy deployments:

Curve-Convex sUSD: 50%
Convex for Frax DOLA: 15%
Stargate USDC: 25%
Convex for Frax FraxUSDC: 5%
Pool Buffer: 5%

**Comment by virendrapatidar** [comment]
Updated weight and submitted transactions.
