### ISSUE TITLE
New Weight updates for vaFRAX

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#211]
Understanding that any new strategy deployments may be delayed through the new year, looking to optimize weight across existing strategy deployments:

Curve-Convex FraxUSDC: 78%
Convex for Frax DOLA: 15%
Convex for Frax FraxUSDC: 1%
Pool Buffer: 6%

Temporary larger pool buffer awaiting weight rampups in the other strategies

**Comment by virendrapatidar** [comment]
Weight updated and rebalance called.
