### ISSUE TITLE
vaUSDC weight updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#212]
Pending deployment of #206 

Target the following weights:

Stargate: 40%
Convex DOLA: 25%
Convex for Frax DOLA: 15%
Convex for Frax FraxBP: 15%
Pool Buffer: 5%

Once the Convex DOLA strategy is ramped up, we can pull funds out of the Convex for Frax DOLA strategy and continue to increase weight in Convex for Frax FraxBP

**Comment by virendrapatidar** [comment]
Convex DOLA: First rebalance done with 3% weight.

**Comment by virendrapatidar** [comment]
Convex_dolafraxbp_USDC : First rebalance done with 3% weight.

**Comment by virendrapatidar** [comment]
Convex_dolafraxbp_USDC : Second rebalance was done and it reported minor loss.
```
profit : 0
loss : 150289
payback : 0
strategyDebt : 8407426347
poolDebt : 273913523074
creditLine : 83439
```

**Comment by rokso** [comment]
@virendrapatidar why it reported loss?

**Comment by virendrapatidar** [comment]
This is Curve/Convex strategy and reports loss due to deposit slippage.

**Comment by virendrapatidar** [comment]
@green-jeff @rokso 

Convex-SUSD4Pool-USDC : has 50% weight and we need to reduce it to 0.
We can't increase stargate weight till we have curve exchanve deployed.
vaUSDC pool is relatively small. Can we allocate Convex-SUSD4Pool-USDC to some other strategy instead of increaseing to Stargate ?

**Comment by virendrapatidar** [comment]
Nonce 957 proposed to update swapper for stargate strategy. This new routed swapper has Curve exchange support

**Comment by virendrapatidar** [comment]
Nonce 957 proposed to update swapper for stargate strategy. This new routed swapper has Curve exchange support

**Comment by virendrapatidar** [comment]
STG => USDC default route added in new swapper as part of [txn](https://etherscan.io/tx/0x6381174113196d2afdead355b7a50a31aef1973658f06f81909c87ca8208cf9f)

**Comment by virendrapatidar** [comment]
Weight updated and rebalance done.
Convex DOLA: 25%
Convex for Frax DOLA: 15%
Convex for Frax FraxBP: 15%

Stargate: 40% weight updated but rebalance is failing `error: execution reverted: Stargate: not enough lp to redeem`
Debug Txn [here](https://dashboard.tenderly.co/virendrapatidar/project/simulator/a11518b4-6bea-40d8-aaa3-0af8ee94e75f?trace=0.6.1.0)

**Comment by virendrapatidar** [comment]
Kept Stargate strategy rebalance at 25% only and called rebalance. 

The Stargate to USDC swap is failing. [Txn](https://dashboard.tenderly.co/tx/mainnet/0xebdf8fc2572ecca3edfd990148912eb2912ac559ecdab23a18aa2b49e07ab9b2?trace=0.1.2.2.0.0.2.0.1.0.0.0.0.3.0) 

I double checked the default routing added (Stargate => USDC using curve exchange) in [txn] for(https://etherscan.io/tx/0x6381174113196d2afdead355b7a50a31aef1973658f06f81909c87ca8208cf9f) and this is okay

Run the default routing and swap test for StarGate => USDC using curve exchange and this is working fine for same amount which is failing (290140727355882547423) in rebalance. 
UT code [here](https://github.com/bloqpriv/one-oracle/blob/main/test/swapper/RoutedSwapper.test.ts#L281-L327)

**Comment by rokso** [comment]
Looks like approve issue. Strategy needs to give STG approval to RoutedSwapper. This is new swapper.

**Comment by virendrapatidar** [comment]
@rokso Approval is there. 
I spent sometime with @marcelomorgado on this

1 - We have unit test for curveExchange STG => USDC and it works only with 
```
const params: CurveSwapParams = [
          [0, 1, 3],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
        ]
```
2 - We have unit test for routed swapper STG => USDC and it works with 
```
const params: CurveSwapParams = [
          [0, 1, 3],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
        ]
```
or
```
const params: CurveSwapParams = [
          [0, 1, 4],
          [0, 0, 0],
          [0, 0, 0],
          [0, 0, 0],
        ]
```
3. In strategy fork test, I have added using default route as `[0, 1, 3]` and ` [0, 1, 4]` and it's not working with both.

**Comment by virendrapatidar** [comment]
- Updated default route to `[0, 1, 3]` on swapper . [Txn](https://etherscan.io/tx/0xa028a3c4ce515c23c7047b46a154ec2071b5afcfe6e36648cf157b8d3b27bfd1)

- Rebalance again [txn](https://ethtx.info/mainnet/0xbe7b054c47468ae446eaa8c0e3ccbc99aa746eb3e2ea6c2850736c6a1e94f53c/)

**Comment by marcelomorgado** [comment]
Update, @virendrapatidar update the path to use type `3` and the 2nd tx error is slightly different:

The 1st tx: https://ethtx.info/mainnet/0xebdf8fc2572ecca3edfd990148912eb2912ac559ecdab23a18aa2b49e07ab9b2/ failed due to trasfeFrom
But the 2nd tx https://ethtx.info/mainnet/0xbe7b054c47468ae446eaa8c0e3ccbc99aa746eb3e2ea6c2850736c6a1e94f53c/ is failing after that on actual swap execution (edited)

**Comment by rokso** [comment]
@marcelomorgado @virendrapatidar very first transaction in tenderly is failing on safeTransferFrom and due to not having allowance. At least tenderly is saying so and this has nothing to do with path.

**Comment by rokso** [comment]
RoutedSwapper has old version of CurveExchange which was causing failure. Once new version of exchange is added in swapper, everything is working as expected.

**Comment by virendrapatidar** [comment]
Weight updated to 40% for stargate strategy and rebalance is done.
Closing this ticket as completed.
