### ISSUE TITLE
vaFRAX updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#213]
Pending deployment of #207 

Convex FraxUSDC: 53%
Convex DOLA: 25%
Convex for Frax DOLA: 15%
Convex for Frax FraxUSDC: 5%

**Comment by virendrapatidar** [comment]
Convex_dolafraxbp_FRAX : Rebalance with 4.5% weight.

**Comment by virendrapatidar** [comment]
Another Rebalance done at 4.5% weight, loss was reported (1.14 frax)

```
profit :0
loss :1142520850540819445
payback :0
strategyDebt :12229219563563747525681
poolDebt :2183792134901586931160803
creditLine :17137812758112291
```

**Comment by virendrapatidar** [comment]
The current weight is as below. In the next run will update the final weight.

Convex FraxUSDC: 65%
Convex DOLA: 12%
Convex for Frax DOLA: 15%
Convex for Frax FraxUSDC: 5%

**Comment by virendrapatidar** [comment]
Updated final weight

Convex FraxUSDC: 53%
Convex DOLA: 25%
Convex for Frax DOLA: 15%
Convex for Frax FraxUSDC: 5%
