### ISSUE TITLE
Deploy Alpha Homora Deposit strategy to vaDAI

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#214]
Deploy Alpha Homora deposit DAI strategy to vaDAI pool.

Alpha Homora is low-medium TVL, high APY. Good boost for DAI pool while other sources remain lower APY.

**Comment by virendrapatidar** [comment]
Multisig Nonce 953 proposed to add AlphaLend strategy for vaDAI pool.

**Comment by virendrapatidar** [comment]
Multisig Nonce 953 executed.
