### ISSUE TITLE
Deploy Compound v3 Borrow USDC strategy to vaLINK

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#215]
Compound v3 currently offers optimal borrow rates for LINK. This will allow us to earn positive yield while link pool is otherwise maintaining small APY opportunities overall.

**Comment by rokso** [comment]
@virendrapatidar We will deploy this once audit branch is merged in main.

**Comment by virendrapatidar** [comment]
Ok, Sure.

**Comment by rokso** [comment]
@green-jeff just for clarity, we want to use CompoundV3 borrow, which deposit LINK, borrow USDC and supply USDC into vaUSDC. Correct?

**Comment by green-jeff** [comment]
That is correct

**Comment by virendrapatidar** [comment]
Multisig Nonce 954 proposed to add a Compound V3 strategy for vaLINK pool.

**Comment by virendrapatidar** [comment]
Multisig Nonce 954 executed.
