### ISSUE TITLE
vaETH Weight updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#216]
Looking to split TVL across Aave and Euler since both are fluctuating as most competitive rates. Also ramping weight down in Stargate as we continue to get hit with sandwiches, putting some back into Alpha Homora for the meantime:

Aave Borrow DAI: 50%
Euler Borrow DAI: 28%
Stargate: 10%
Alpha Homora: 10%
Pool Buffer: 2%

**Comment by virendrapatidar** [comment]
@green-jeff 

Weight updated and rebalanced as mentioned.
