### ISSUE TITLE
vaDAI weight updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#217]
Alpha Homora strategy deployed for DAI. Now to update weight:

80%: Compound Leverage
20%: Alpha Homora

We are pulling weight off of Curve sUSD altogether. Note that due to bad debt, real weight on these strategies is approximately 64% / 16%

**Comment by virendrapatidar** [comment]
Alpha Homora: Did first rebalance with 1.5% weight.

**Comment by virendrapatidar** [comment]
Alpha Homora: second rebalance in profit

```
profit : 1165138478155106841
loss : 0
payback : 0
strategyDebt : 9207044835889866891586
poolDebt : 2910719968925098349700081
creditLine : 0
```

**Comment by virendrapatidar** [comment]
Updated final weight. 
77%: Compound Leverage
20%: Alpha Homora
