### ISSUE TITLE
vaLINK Weight Updates

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#218]
With Compound v3 deployed, push all LINK weight into the strategy:

Compound v3 Borrow USDC: 95%
Pool Buffer: 5%

**Comment by virendrapatidar** [comment]
First Rebalance done with 10% weight.

**Comment by virendrapatidar** [comment]
Added COMP => ChainLink default route using Sushiswap.

**Comment by virendrapatidar** [comment]
Second rebalance does report profit

```
profit :45846866129818754
loss :0
payback :0
strategyDebt :1262556237580840379020
poolDebt :1297238638537149377670
creditLine :0
```

**Comment by virendrapatidar** [comment]
Weight updated.
