### ISSUE TITLE
vaFRAX Weight Update

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#220]
Update strategies to vaFRAX pool as follows:

* Convex FraxUSDC: 43%
* Convex DOLA: 28%
* ConvexForFrax FraxUSDC: 15%
* ConvexForFrax DOLA: 12%

**Comment by green-jeff** [comment]
Note, there was a large deposit to the FRAX pool of 500,000 FRAX. (Total Pool TVL increased from 2,215,000 FRAX => 2,715,000 FRAX)

Weight adjustments here reflect amounts that should minimize swapping in and out of Curve.

The following strategies should not see a change in TVL

Convex FraxUSDC
ConvexForFrax DOLA

New TVL should all go into 

ConvexForFrax FraxUSDC
Convex DOLA

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 

Weight updated as mentioned. The new 500K FRAX deposited to 
ConvexForFrax FraxUSDC
Convex DOLA
