### ISSUE TITLE
Harvest EUL Rewards

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#225]
Our Euler strategy on vaETH (Deposit ETH Borrow DAI) does not yet seem to have claimed any EUL rewards.

How can we harvest these rewards and make sure the routing is protected against sandwiches?

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @rokso 

Manual claim done using rewardDistributor contract by calling `claim` method.
Here is the [txn](https://etherscan.io/tx/0xc1d3c75b4aef59cc05ad53995399e150f91f3307b94760d18b2a4b9accc0af65) 

Claim amount : 117.65 EUL.

Will further check for converting them to collateral.

**Comment by virendrapatidar** [comment]
Default route added using uniV3 pool (EUL/WETH). It has liquidity of 200K. Do not see liquidity for EUL on UniV2/Suhsi/Curve etc. 

The rebalance does not swap EUL to WETH (Collateral). I see swapping is done only in `harvestEul` so we need to wait for next claim process using strategy

**Comment by rokso** [comment]
@virendrapatidar which strategy?

**Comment by virendrapatidar** [comment]
https://etherscan.io/address/0x46667F3771514E7D76c3948AcAD6DdA378db63f5

**Comment by patidarmanoj10** [comment]
Good to close this?

**Comment by virendrapatidar** [comment]
@patidarmanoj10 - We have another issue open. I will do automation as part of 
https://github.com/bloqpriv/vesper-contracts/issues/396 so closing it.
