### ISSUE TITLE
Rebalance vaFRAX Weight

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#227]
We are still working towards getting the Frax strategies into a steady state, which will ultimately do with minimal weight in the Convex FraxUSDC strategy. There was another large deposit today ($750k) so the weight updates below are intended to minimize deposit/withdrawal from strategies:

Convex FraxUSDC: 33% (same absolute TVL as before)
Convex DOLA: 23% (same absolute TVL as before)
ConvexForFrax FraxUSDC: 25% (increase absolute TVL)
ConvexForFrax DOLA: 17% (increase absolute TVL)

Note that all strategies can be rebalanced about 24 hours from now (targetting 7 day rebalance) with the exception of ConvexForFrax DOLA. That strategy will need another +2 days until it may rebalance. So the new TVL to that strategy (roughly 241k FRAX) will sit as extra pool buffer

**Comment by virendrapatidar** [comment]
@green-jeff 
I have updated the weights as mentioned and rebalanced all strategies. 
When we reduce weight for a strategy, we have to rebalance it to pull out funds from the protocol. This fund will be later deployed to strategies with increased weight.
