### ISSUE TITLE
vaDAI Rebalance: Increase weight in Stargate Strategy

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#230]
We need to scrape higher yield on DAI wherever we can, especially with Rocket Pool launching and paying 1.5% interest rate - we need to safely offer higher yield than that.

Compound leverage strategy has been good, but its yield is trending down for some weeks now. Stargate yield has been high.

Rebalance weight as follows:
* 83% Compound leverage
* 15% Stargate Deposit
* 2% Pool Buffer

Due to bad debt, real weight will look something like:
* 66.4% Compound Leverage
* 20% Rari Fuse
* 12% Stargate
* 1.6% Pool buffer

Stargate strategy has been deployed but not implemented, so please do iterative rampup of 1% -> 5% -> 15% 

Also ensure that STG route is properly added

This should increase end user pool APY from 1.8% to 2.5%

**Comment by virendrapatidar** [comment]
@green-jeff @patidarmanoj10 

First round
Reduced weight for Compound leverage to 75% and rebalance
Increased weight for Stargate to 20% and it has deployed 18K worth of DAI.

**Comment by virendrapatidar** [comment]
Added unittest to swap STG to DAI using curve exchange 
PR : https://github.com/bloqpriv/one-oracle/pull/359

**Comment by virendrapatidar** [comment]
Multisig nonce 967 proposed 
- using curve exchange default route for STG => DAI swap.
- update swapper for stargate strategy (vaDAI) pool.

**Comment by virendrapatidar** [comment]
@green-jeff - I will do it in a total of 3 iterations so consider we will have full weight by coming Mon/Tue

**Comment by green-jeff** [comment]
Great!

**Comment by virendrapatidar** [comment]
967 executed. Strategy have a new swapper that can swap STG => Collateral using curve exchange.

**Comment by virendrapatidar** [comment]
rebalance done and STG is converted into DAI.

**Comment by virendrapatidar** [comment]
Additional 150K worth of DAI deployed to Stargate strategy.

**Comment by virendrapatidar** [comment]
rebalance done with 31% weight, another 85K worth of DAI deployed.
