### ISSUE TITLE
vaFRAX rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#232]
There was another recent, large deposit (600k FRAX) that we would like to absorb into existing strategies with minimal rebalancing.

Adjust strategy weight targets as follows:

ConvexForFrax FraxBP: 29%
Convex FraxBP: 29%
Convex DOLA: 20%
ConvexForFrax DOLA: 20%

This should translates to ConvexForFrax FraxBP and ConvexForFrax DOLA strategies receiving the new deposits, and Convex FraxBP and Convex DOLA strategies maintaining the same atomic TVL (and lower weight as a result)

**Comment by patidarmanoj10** [comment]
@virendrapatidar lets do it so new fund start earning yield sooner than later.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 

Weight updated as mentioned and rebalance is done. 
New fund deployed to ConvexForFrax FraxBP and ConvexForFrax DOLA strategies.
