### ISSUE TITLE
Optimism Deployment: Curve

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#236]
Deploy the following Curve strategies to Optimism:

ETH: sETH-ETH LP
USDC: sUSD LP

This should be second priority strategy behind Alpha Homora #235 unless there is difficulty with Alpha, then this can be first priority.

**Comment by virendrapatidar** [comment]
Deployed vaETH pool with Curve Strategy
Testing done
1. Approve WETH to pool proxy
2. Weight update 
3. Deposit 0.8 WETH
4. Rebalance
5. Withdraw 
6. Deposit
7. Rebalance

ETH deposit [simulation](https://dashboard.tenderly.co/virendrapatidar/project/simulator/e3f4f546-8dd8-46dd-a21c-e54ab214e621) is working but not able to deposit on Optimism mainnet using Metamask.

Contract address 
```
 "vaeth": {
        "pool": {
          "proxyAdmin": "0x1aF1055214d6A2FD8dbC8e257610c81516f838Be",
          "proxy": "0xCcF3d1AcF799bAe67F6e354d685295557cf64761",
          "implementation": "0x655952146E18ec662bF2BC7cC3d85247fd5d86D4",
          "poolAccountant": {
            "proxyAdmin": "0xAf245C4Fb15Cb8f9cE72E387F71F0eEB418e7BE9",
            "proxy": "0x59e9117a1106EDd3b3CfEE71eb2FE502f356482D",
            "implementation": "0x1BdA287BF5d14b70C0A2805bc15049C9fA43B428"
          }
        },
        "strategies": {
          "Curve_sETH_ETH": "0xb1458639956402B3f96E514f5A7dbe1bbC58A981"
        }
      }
```

**Comment by virendrapatidar** [comment]
Deployed vaUSDC pool with Curve Strategy
Testing done

1. Approve USDC to pool proxy
2. Weight update to 96%
3. Deposit 150 USDC
4. Rebalance
5. Withdraw 140 USDC
6. Deposit 145 USDC
7. Rebalance

```
"vausdc": {
        "pool": {
          "proxyAdmin": "0x1aF1055214d6A2FD8dbC8e257610c81516f838Be",
          "proxy": "0x539505Dde2B9771dEBE0898a84441c5E7fDF6BC0",
          "implementation": "0x5c39Cd35889247D30090eF004d05580356791183",
          "poolAccountant": {
            "proxyAdmin": "0xAf245C4Fb15Cb8f9cE72E387F71F0eEB418e7BE9",
            "proxy": "0x476F833357961bF4Dc144d13C0A6326E54b94dA9",
            "implementation": "0x1BdA287BF5d14b70C0A2805bc15049C9fA43B428"
          }
        },
        "strategies": {
          "Curve_sUSD_USDC": "0x6A12FA3eD48B1404EB973bCdF2d4DF390E497544"
        }
```

**Comment by virendrapatidar** [comment]
@patidarmanoj10 

Did 3rd rebalance for vaETH pool and Curve strategy is loss-making.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 
Added default route to  convert reward tokens OP => WETH and CRV => WETH using UniV3
claimAndSwapRewards method was called before rebalance and it reported profit.

**Comment by virendrapatidar** [comment]
Added default route for  OP => USDC as well. 
 claimAndSwapRewards method converted OP to USDC.
