### ISSUE TITLE
Deploy vacbETH with Euler borrow USDC

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#240]
Deploy Vesper Aggressive cbETH pool using the USDC borrow strategy:

Deposit cbETH => Borrow USDC => Deposit USDC to Vesper

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @rokso 

I see vacbETH config is present in `develop` branch and not on main branch.
The config and test were recently added as part of PR https://github.com/bloqpriv/vesper-contracts/pull/456
We are doing some refactoring in pool code. Is it okay to deploy this pool from develop branch or we should wait till develop is merged into main branch?

**Comment by patidarmanoj10** [comment]
meanwhile can you unit test euler strategy for vaCBETH pool?

**Comment by patidarmanoj10** [comment]
@virendrapatidar We want to deploy from main branch.  Merge develop to main will take some time . We dont want to rush to merge develop into main. 
We should have PR https://github.com/bloqpriv/vesper-contracts/pull/456 changes to main and then deploy cbvaETH.

**Comment by virendrapatidar** [comment]
Ok

**Comment by patidarmanoj10** [comment]
Ideally this PR could go to main branch. 

I know when we merge develop to main in near future, we will get conflict in this files. We will deal with that conflict.

**Comment by patidarmanoj10** [comment]
cc @rokso

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @rokso 

I am using cherry-pick for this commit and will run UTs.

**Comment by virendrapatidar** [comment]
Deposit cbETH => Borrow USDC => Deposit USDC to Vesper

Configuration and Unit tests okay. 
PR : https://github.com/vesperfi/vesper-pool-ops/issues/240

**Comment by virendrapatidar** [comment]
current gas is [272 Gwei](https://etherscan.io/gastracker).
I will deploy it during non US working hours.

**Comment by rokso** [comment]
@patidarmanoj10 @virendrapatidar I prefer to merge develop to main and then deploy. 
Why?
- There is not much  logic change which can break things but there are good changes done in develop
- Curve rewardToken fetch was a good change
- All changes done in pool so far or good changes
I vote to merge develop to main and then deploy

**Comment by virendrapatidar** [comment]
@patidarmanoj10 - I am also of opinion we should merge develop into main and then deploy.

**Comment by patidarmanoj10** [comment]
Go ahead.

**Comment by virendrapatidar** [comment]
- Pool and strategy deployed as part of PR https://github.com/bloqpriv/vesper-contracts/pull/472
- First Sanity testing is done: Approval, Deposit, Rebalance, Withdraw

Will add the default route using uniV3 and do a second rebalance.

**Comment by rokso** [comment]
I am glad that I raised develop to main merge PR and it worked out.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @rokso 

- The default routes are added.
- The second rebalance was failing due to a very small amount of swap. In fork, if I donate 0.02 USDC (Borrow token) to strategy then the second rebalance is working.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 , @rokso 

Donated 1 USDC to strategy and second rebalance done on [mainnet](https://etherscan.io/tx/0x9053f6876885372ddcc04c8e9f59a303d1d56b0cacfa0a05d832a86e8a5b54a7)
Rebalance consumes 1,211,283 gas.

**Comment by virendrapatidar** [comment]
VACBETH  pool contract address

```
  "vacbeth": {
        "pool": {
          "proxyAdmin": "0xa924b6725f7eA2650c6E3F09eb0d36a76486c5B0",
          "proxy": "0x650CD45DEdb19c33160Acc522aD1a82D9701036a",
          "implementation": "0x91f92F75E547Db066c39DEa4d4a8B45f4B8EDE4a",
          "poolAccountant": {
            "proxyAdmin": "0xB5144e9EAD98D7c0B47B7549f3b2E0b89eB585C6",
            "proxy": "0xBDF903d93f5625950670f487dB4d9157062474FA",
            "implementation": "0x2a7534a2A4293068931e7D287EfBcE7889031794"
          }
        },
        "poolRewards": {
          "proxyAdmin": "0x655845AC2Db0c1955815bDc33F0270bC37e03D23",
          "proxy": "0x5323427696CBce0e15d2e21627E8Aa646a5F5D83",
          "implementation": "0x90bb3E3AA5Fa88f0a83Dcb9485f65D2592f4307E"
        },
        "strategies": {
          "Euler_Vesper_Xy_CBETH_USDC": "0x2B5DE50A1DB84DD2DC66146Cd513d2688394b609"
        }
      }
```

**Comment by virendrapatidar** [comment]
Updated default routing for exactOutput and rebalance is okay.
