### ISSUE TITLE
vaFRAX Weight Rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#241]
Another new large deposit (650k) to the FRAX pool, looking to deploy it in a way that minimizes slippage, same as prior:

New weight targets:

* ConvexForFrax FraxBP: 33% (atomic weight increase)
* Convex FraxBP: 25% (same atomic weight as before)
* ConvexForFrax DOLA: 23% (atomic weight increase)
* Convex DOLA: 17% (same atomic weight as before)

**Comment by virendrapatidar** [comment]
@patidarmanoj10 @green-jeff 

Rebalance done.
