### ISSUE TITLE
vaUSDC rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#243]
We've recently received a large deposit to USDC (~180k) in order to deploy in a timely manner without incurring too much slippage, let's ramp up the previously used Stargate strategy with the new funds.

Intention is to keep both existing strategies the same atomic weight (lower weight %) and add all new weight into a stargate strategy.

New weights as follows:
* Stragte USDC: 36%
* Convex DOLA: 32%
* ConvexForFrax FraxBP: 29%
* Pool buffer: 3%

**Comment by virendrapatidar** [comment]
@green-jeff - The ~180K USDC were already deployed to existing strategies without weight update. This was done before I could see your message. 

Please let me know how you want to handle it now.
