### ISSUE TITLE
vaDAI Rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#244]
DAI yield is dwindling on both Compound and Stargate. Let's reactivate our sUSD Curve-Convex strategy to maintain some yield:

* Compound leverage: 50%
* Curve-Convex sUSD: 50%

**Comment by patidarmanoj10** [comment]
@green-jeff is there any slippage loss if 50% goes to convex?

**Comment by green-jeff** [comment]
@patidarmanoj10 small slippage, <0.1% according to the Curve frontend. Can do it across two rebalances:

Compound Leverage: 75%
Curve-Convex sUSD: 25%

If that works better

**Comment by patidarmanoj10** [comment]
set compound leverage to 50%. 
Convex-SUSD4Pool-DAI to 10%. will gradually increase from here to 50%.

**Comment by patidarmanoj10** [comment]
Done.  compound leverage 50, Convex-SUSD4Pool-DAI: 40

**Comment by patidarmanoj10** [comment]
Plz open another gh issue when we ready to ramp up further after couple of days.

**Comment by patidarmanoj10** [comment]
Rebalance done 250k  moved .
