### ISSUE TITLE
vaUSDC Rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#245]
fraxBP yield is low, and additionally causes some limitations due to LP lockup.

Let's migrate USDC TVL to Stargate and push DOLA TVL towards the higher yielding Frax portion of the strategy:

* Stargate: 45%
* ConvexForFrax DOLA: 10%
* Convex DOLA: 40%

This will remove all TVL from ConvexForFrax FraxBP and begin to ramp up ConvexForFrax DOLA

Intention is to ultimately move all DOLA denominated TVL to ConvexForFrax DOLA

**Comment by patidarmanoj10** [comment]
@zhhuffman These are current Convex frax stratregies are in use. which one we want to reduce?

Convex_dolafraxbp_USDC
ConvexForFrax_fraxusdc_USDC

Do we want to add to ConvexForFrax_dolafraxbp_USDC?

**Comment by patidarmanoj10** [comment]
There is no other dola stratregy in queue where we want to ramp up tvl.

**Comment by green-jeff** [comment]
@patidarmanoj10 

ConvexForFrax_dolafraxbp_USDC: 0% -> 10%
Convex_dolafraxbp_USDC: 50% -> 40%

ConvexForFrax_dolafraxbp_USDC has no current weight but has been used previously

**Comment by patidarmanoj10** [comment]
weight updated. will have to wait for low gas

**Comment by patidarmanoj10** [comment]
Done.
