### ISSUE TITLE
vaUSDC Rebalance

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#249]
Looking to migrate DOLA weight to Frax strategy and ramp migrate other weight to Stargate:

Stargate: 45%
ConvexForFrax_dolafraxbp_USDC: 25%
Convex_dolafraxbp_USDC: 25%
Pool Buffer: 5%

**Comment by patidarmanoj10** [comment]
Update this two weights 
ConvexForFrax_dolafraxbp_USDC: 25%
Convex_dolafraxbp_USDC: 25%

but there is ConvexForFrax_fraxusdc_USDC that has 45% weight. what to do with this one?

**Comment by patidarmanoj10** [comment]
@zhhuffman ^

**Comment by green-jeff** [comment]
@patidarmanoj10 0% weight for that pool

**Comment by patidarmanoj10** [comment]
Presently ConvexForFrax_fraxusdc_USDC is in lock-in period.

**Comment by green-jeff** [comment]
@patidarmanoj10 we should be able to execute this whenever now

**Comment by green-jeff** [comment]
@patidarmanoj10 USDC TVL is up. Per our conversation, looking to put all new TVL into Stargate and ConvexForFrax only, and start to wind down Convex too. Next rebalance we can exit the Convex strategy altogether.

For this rebalance, let's do:

Stargate: 48%
ConvexForFrax_dolafraxbp_USDC: 35%
Convex_dolafraxbp_USDC: 12%

**Comment by patidarmanoj10** [comment]
Done
