### ISSUE TITLE
vacbETH Aave v3 deployment

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#250]
vacbETH can no longer access Euler strategy.

Deploy vacbETH Deposit to Aave v3 Borrow DAI @ 50% LTV

We will look to deploy all TVL to this strategy until further notice

**Comment by rokso** [comment]
@green-jeff We have upper and lower limit of LTV. We borrow at lower limit and repay if borrow goes above upper limit. So it looks like lower is 50% what should be the upper limit?

**Comment by green-jeff** [comment]
50%/60%

**Comment by rokso** [comment]
Strategy is deployed and weight is set.
