### ISSUE TITLE
Avalanche vaUSDC.e weight update

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#255]
Migrate all weight to Trader Joe deposit strategy:

Trader Joe Deposit USDC.e: 97%
Pool Buffer: 3%

**Comment by patidarmanoj10** [comment]
TraderJoe strategy is reverting in rebalance. Debugging it.

**Comment by patidarmanoj10** [comment]
Market is still paused after recent depeg event.  https://twitter.com/traderjoe_xyz/status/1634457046778085377?s=20

**Comment by patidarmanoj10** [comment]
Done
