### ISSUE TITLE
Deploy vaUNI pool with Compound leverage strategy 

### ISSUE THREAD

**Issue by virendrapatidar** [vesperfi/vesper-pool-ops#77]
Deploy vaUNI pool with Compound leverage strategy.
Deploy it only after PR is approved and merged: https://github.com/bloqpriv/vesper-pools-v3/pull/1007

mainnet
```
npm run deploy -- --pool VAUNI --network mainnet --release 4.0.1 --deploy-params '{"tags": "deploy-vPool"}'

npm run deploy -- --pool VAUNI --network mainnet --release 4.0.1 --deploy-params '{"tags": "deploy-strategy"}' --strategy-name CompoundLeverageStrategyUNI

```

After deployment
1. Update debtRatio/weitht of newly deployed CompoundLeverageStrategyUNI strategy to 9500

cc @patidarmanoj10

**Comment by patidarmanoj10** [comment]
This is new pool . vaUNI

**Comment by virendrapatidar** [comment]
@jcvernaleo - This is ready for deployment.
cc @patidarmanoj10

**Comment by patidarmanoj10** [comment]
Absolute.
