### ISSUE TITLE
Deploy  Trader Joe and Benqi compound leverage strategies for Avalanche pools

### ISSUE THREAD

**Issue by virendrapatidar** [vesperfi/vesper-pool-ops#81]
Deploy  Trader Joe and Benqi compound leverage strategies for Avalanche pools
Deployment to be done after PR is merged: https://github.com/bloqpriv/vesper-pools-v3/pull/1005
@patidarmanoj10 : Please confirm the weight for each strategy. Weight can be updated after deployment.

**Deploy  Trader Joe compound leverage for Avalanche pool**

```
npm run deploy -- --pool vaWETH --network avalanche --release 4.0.1 --deploy-params '{"tags": "deploy-strategy"}' --strategy-name TraderJoeCompoundLeverageStrategyAvalancheWETH --target-chain avalanche
```

**Deploy  Benqi compound leverage for Avalanche pool**

```
npm run deploy -- --pool vaAVAX --network avalanche --release 4.0.1 --deploy-params '{"tags": "deploy-strategy"}' --strategy-name BenqiCompoundLeverageStrategyAvalancheAVAX --target-chain avalanche

npm run deploy -- --pool vaDAI --network avalanche --release 4.0.1 --deploy-params '{"tags": "deploy-strategy"}' --strategy-name BenqiCompoundLeverageStrategyAvalancheDAI --target-chain avalanche

```

**Comment by jcvernaleo** [comment]
@virendrapatidar benqi stratgies done (#83 )

Just want to confirm, are the trader joe ones ready for me to deploy for all pools?

**Comment by virendrapatidar** [comment]
@jcvernaleo, Yes trader Joe is ready as well.
Need to confirm weight from @patidarmanoj10

**Comment by jcvernaleo** [comment]
Actually, trader joe was already deployed (see #76) so I believe everything for this issue is done.
