### ISSUE TITLE
Avalanche Deployment: Curve

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#89]
Deploy The following Curve strategies to Avax pools with 0 weight:

a3pool
* USDC
* DAI

renBTC
* WBTC

**Comment by patidarmanoj10** [comment]
@virendrapatidar Deploy all weight of USDC, DAI pool of Avalanche to a3Pool strategy.

**Comment by virendrapatidar** [comment]
Rebalance done again today and looking good.

**Comment by virendrapatidar** [comment]
@patidarmanoj10 - Which strategy do we need to deploy for renBTC? I do not find it.

**Comment by virendrapatidar** [comment]
Deploy renBTC once https://github.com/bloqpriv/vesper-pools-v3/issues/1173 is done.

**Comment by virendrapatidar** [comment]
New deployment ticket created for renBTC https://github.com/bloqpriv/vesper-pools-v3/issues/1204
