### ISSUE TITLE
Avalanche Deployment: BenQi, TraderJoe Leverage

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#90]
Deploy leverage strategies on BenQi, TraderJoe for ALL Avax pools

**Comment by patidarmanoj10** [comment]
@virendrapatidar We have Benqi leverage for all pools. need to deploy tradejo leverage .

**Comment by virendrapatidar** [comment]
We have trader joe leverage for 3 pools.

TraderJoeLeverageStrategyAVAX
TraderJoeLeverageStrategyUSDC
TraderJoeLeverageStrategyWETH

**Comment by virendrapatidar** [comment]
We have GH https://github.com/bloqpriv/vesper-pools-v3/issues/1203 and https://github.com/bloqpriv/vesper-pools-v3/issues/1202 for DAI and WBTC pool open.

Closing this ticket.
