### ISSUE TITLE
Avax Deployment: Alpha Homora

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#91]
Deploy Alpha Homora strategies for all Avax pools

**Comment by patidarmanoj10** [comment]
@virendrapatidar Strategy name: AlphaLendAvalancheStrategy

**Comment by virendrapatidar** [comment]
Deployed for vaWETH and vaAVAX as part of https://github.com/bloqpriv/vesper-pools-v3/issues/1228

**Comment by virendrapatidar** [comment]
Created GH https://github.com/bloqpriv/vesper-pools-v3/issues/1237 for DAI, WBTC and AVAX deployment.
