### ISSUE TITLE
Avax Deployment: BenQi Borrow

### ISSUE THREAD

**Issue by green-jeff** [vesperfi/vesper-pool-ops#92]
Deploy the following Borrow strategies on BenQi @ 45% LTV:

* Supply Avax Borrow USDC
* Supply WBTC Borrow USDC
* Supply WETH Borrow USDC

**Comment by patidarmanoj10** [comment]
@zhhuffman I dont this is going to be profitable . 

Supply earning is less than borrow cost of USDC

**Comment by patidarmanoj10** [comment]
Stale. Closing . Reopn if we want to do this in future.
